#ifndef GRAPHICS_KEYCODES_H
#define GRAPHICS_KEYCODES_H

#define		KEYCODE_KEY_UNKNOWN -1
#define 	KEYCODE_KEY_SPACE   32
#define 	KEYCODE_KEY_APOSTROPHE   39 /* ' */
#define 	KEYCODE_KEY_COMMA   44 /* , */
#define 	KEYCODE_KEY_MINUS   45 /* - */
#define 	KEYCODE_KEY_PERIOD   46 /* . */
#define 	KEYCODE_KEY_SLASH   47 /* / */
#define 	KEYCODE_KEY_0   48
#define 	KEYCODE_KEY_1   49
#define 	KEYCODE_KEY_2   50
#define 	KEYCODE_KEY_3   51
#define 	KEYCODE_KEY_4   52
#define 	KEYCODE_KEY_5   53
#define 	KEYCODE_KEY_6   54
#define 	KEYCODE_KEY_7   55
#define 	KEYCODE_KEY_8   56
#define 	KEYCODE_KEY_9   57
#define 	KEYCODE_KEY_SEMICOLON   59 /* ; */
#define 	KEYCODE_KEY_EQUAL   61 /* = */
#define 	KEYCODE_KEY_A   65
#define 	KEYCODE_KEY_B   66
#define 	KEYCODE_KEY_C   67
#define 	KEYCODE_KEY_D   68
#define 	KEYCODE_KEY_E   69
#define 	KEYCODE_KEY_F   70
#define 	KEYCODE_KEY_G   71
#define 	KEYCODE_KEY_H   72
#define 	KEYCODE_KEY_I   73
#define 	KEYCODE_KEY_J   74
#define 	KEYCODE_KEY_K   75
#define 	KEYCODE_KEY_L   76
#define 	KEYCODE_KEY_M   77
#define 	KEYCODE_KEY_N   78
#define 	KEYCODE_KEY_O   79
#define 	KEYCODE_KEY_P   80
#define 	KEYCODE_KEY_Q   81
#define 	KEYCODE_KEY_R   82
#define 	KEYCODE_KEY_S   83
#define 	KEYCODE_KEY_T   84
#define 	KEYCODE_KEY_U   85
#define 	KEYCODE_KEY_V   86
#define 	KEYCODE_KEY_W   87
#define 	KEYCODE_KEY_X   88
#define 	KEYCODE_KEY_Y   89
#define 	KEYCODE_KEY_Z   90
#define 	KEYCODE_KEY_LEFT_BRACKET   91 /* [ */
#define 	KEYCODE_KEY_BACKSLASH   92 /* \ */
#define 	KEYCODE_KEY_RIGHT_BRACKET   93 /* ] */
#define 	KEYCODE_KEY_GRAVE_ACCENT   96 /* ` */
#define 	KEYCODE_KEY_WORLD_1   161 /* non-US #1 */
#define 	KEYCODE_KEY_WORLD_2   162 /* non-US #2 */
#define 	KEYCODE_KEY_ESCAPE   256
#define 	KEYCODE_KEY_ENTER   257
#define 	KEYCODE_KEY_TAB   258
#define 	KEYCODE_KEY_BACKSPACE   259
#define 	KEYCODE_KEY_INSERT   260
#define 	KEYCODE_KEY_DELETE   261
#define 	KEYCODE_KEY_RIGHT   262
#define 	KEYCODE_KEY_LEFT   263
#define 	KEYCODE_KEY_DOWN   264
#define 	KEYCODE_KEY_UP   265
#define 	KEYCODE_KEY_PAGE_UP   266
#define 	KEYCODE_KEY_PAGE_DOWN   267
#define 	KEYCODE_KEY_HOME   268
#define 	KEYCODE_KEY_END   269
#define 	KEYCODE_KEY_CAPS_LOCK   280
#define 	KEYCODE_KEY_SCROLL_LOCK   281
#define 	KEYCODE_KEY_NUM_LOCK   282
#define 	KEYCODE_KEY_PRINT_SCREEN   283
#define 	KEYCODE_KEY_PAUSE   284
#define 	KEYCODE_KEY_F1   290
#define 	KEYCODE_KEY_F2   291
#define 	KEYCODE_KEY_F3   292
#define 	KEYCODE_KEY_F4   293
#define 	KEYCODE_KEY_F5   294
#define 	KEYCODE_KEY_F6   295
#define 	KEYCODE_KEY_F7   296
#define 	KEYCODE_KEY_F8   297
#define 	KEYCODE_KEY_F9   298
#define 	KEYCODE_KEY_F10   299
#define 	KEYCODE_KEY_F11   300
#define 	KEYCODE_KEY_F12   301
#define 	KEYCODE_KEY_F13   302
#define 	KEYCODE_KEY_F14   303
#define 	KEYCODE_KEY_F15   304
#define 	KEYCODE_KEY_F16   305
#define 	KEYCODE_KEY_F17   306
#define 	KEYCODE_KEY_F18   307
#define 	KEYCODE_KEY_F19   308
#define 	KEYCODE_KEY_F20   309
#define 	KEYCODE_KEY_F21   310
#define 	KEYCODE_KEY_F22   311
#define 	KEYCODE_KEY_F23   312
#define 	KEYCODE_KEY_F24   313
#define 	KEYCODE_KEY_F25   314
#define 	KEYCODE_KEY_KP_0   320
#define 	KEYCODE_KEY_KP_1   321
#define 	KEYCODE_KEY_KP_2   322
#define 	KEYCODE_KEY_KP_3   323
#define 	KEYCODE_KEY_KP_4   324
#define 	KEYCODE_KEY_KP_5   325
#define 	KEYCODE_KEY_KP_6   326
#define 	KEYCODE_KEY_KP_7   327
#define 	KEYCODE_KEY_KP_8   328
#define 	KEYCODE_KEY_KP_9   329
#define 	KEYCODE_KEY_KP_DECIMAL   330
#define 	KEYCODE_KEY_KP_DIVIDE   331
#define 	KEYCODE_KEY_KP_MULTIPLY   332
#define 	KEYCODE_KEY_KP_SUBTRACT   333
#define 	KEYCODE_KEY_KP_ADD   334
#define 	KEYCODE_KEY_KP_ENTER   335
#define 	KEYCODE_KEY_KP_EQUAL   336
#define 	KEYCODE_KEY_LEFT_SHIFT   340
#define 	KEYCODE_KEY_LEFT_CONTROL   341
#define 	KEYCODE_KEY_LEFT_ALT   342
#define 	KEYCODE_KEY_LEFT_SUPER   343
#define 	KEYCODE_KEY_RIGHT_SHIFT   344
#define 	KEYCODE_KEY_RIGHT_CONTROL   345
#define 	KEYCODE_KEY_RIGHT_ALT   346
#define 	KEYCODE_KEY_RIGHT_SUPER   347
#define 	KEYCODE_KEY_MENU   348

#define 	KEYCODE_MOUSE_BUTTON_1   0
#define 	KEYCODE_MOUSE_BUTTON_2   1
#define 	KEYCODE_MOUSE_BUTTON_3   2
#define 	KEYCODE_MOUSE_BUTTON_4   3
#define 	KEYCODE_MOUSE_BUTTON_5   4
#define 	KEYCODE_MOUSE_BUTTON_6   5
#define 	KEYCODE_MOUSE_BUTTON_7   6
#define 	KEYCODE_MOUSE_BUTTON_8   7
#define 	KEYCODE_MOUSE_BUTTON_LAST   KEYCODE_MOUSE_BUTTON_8
#define 	KEYCODE_MOUSE_BUTTON_LEFT   KEYCODE_MOUSE_BUTTON_1
#define 	KEYCODE_MOUSE_BUTTON_RIGHT   KEYCODE_MOUSE_BUTTON_2
#define 	KEYCODE_MOUSE_BUTTON_MIDDLE   KEYCODE_MOUSE_BUTTON_3


#endif